---
AllCops:
  Exclude:
  - vendor/**/*
Documentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
Style/Encoding:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
